[workspace]

[package]
name = "data-test"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "fractal:data-test"
target.path = "wit"
target.world = "micro-app"
